// Quest schema and launch quest definitions
export const QUESTS = [
  // Zone 1: Onboarding (5 quests)
  {
    id: "q_kill_goblins_1",
    title: "Goblin Exterminator I",
    description: "Defeat 25 Goblins in Realm of Light.",
    type: "kill_enemy",
    target: 25,
    zoneId: "realm_of_light",
    enemyName: "Goblin",
    reward: { coins: 50, souls: 0, slayerPoints: 0 },
    repeatable: false,
    prerequisiteIds: [],
    order: 10,
  },
  {
    id: "q_first_stage_clear",
    title: "Pathfinder",
    description: "Reach Stage 2 in Realm of Light.",
    type: "reach_stage",
    target: 2,
    zoneId: "realm_of_light",
    reward: { coins: 100, souls: 1, slayerPoints: 0 },
    repeatable: false,
    prerequisiteIds: [],
    order: 20,
  },
  {
    id: "q_first_boss",
    title: "Boss Slayer I",
    description: "Defeat your first boss.",
    type: "kill_any",
    target: 25, // Threshold to trigger boss; progress on kills
    isBossCheck: true,
    reward: { coins: 200, souls: 2, slayerPoints: 1 },
    repeatable: false,
    prerequisiteIds: [],
    order: 30,
  },
  {
    id: "q_first_prestige",
    title: "Ascendant",
    description: "Prestige for the first time.",
    type: "prestige",
    target: 1,
    reward: { coins: 0, souls: 0, slayerPoints: 2 },
    repeatable: false,
    prerequisiteIds: [],
    order: 40,
  },
  {
    id: "q_first_sp_spend",
    title: "Scholar",
    description: "Spend Slayer Points to unlock your first skill.",
    type: "spend_sp",
    target: 1,
    reward: { coins: 150, souls: 1, slayerPoints: 0 },
    repeatable: false,
    prerequisiteIds: [],
    order: 50,
  },

  // Zone 2: Bridge (4 quests)
  {
    id: "q_unlock_zone2",
    title: "New Horizons",
    description: "Unlock the Whispering Woods.",
    type: "unlock_zone",
    target: 1,
    zoneId: "whispering_woods",
    reward: { coins: 300, souls: 2, slayerPoints: 0 },
    repeatable: false,
    prerequisiteIds: ["q_first_stage_clear"],
    order: 60,
  },
  {
    id: "q_zone2_kills_50",
    title: "Woods Bane",
    description: "Defeat 50 enemies in the Whispering Woods.",
    type: "kill_zone",
    target: 50,
    zoneId: "whispering_woods",
    reward: { coins: 250, souls: 2, slayerPoints: 1 },
    repeatable: false,
    prerequisiteIds: ["q_unlock_zone2"],
    order: 70,
  },
  {
    id: "q_zone2_stage_clear",
    title: "Deep Delver",
    description: "Reach Stage 4 in the Whispering Woods.",
    type: "reach_stage",
    target: 4,
    zoneId: "whispering_woods",
    reward: { coins: 400, souls: 3, slayerPoints: 1 },
    repeatable: false,
    prerequisiteIds: ["q_zone2_kills_50"],
    order: 80,
  },
  {
    id: "q_zone2_souls",
    title: "Soul Collector",
    description: "Earn 5 souls in the Whispering Woods.",
    type: "zone_souls",
    target: 5,
    zoneId: "whispering_woods",
    reward: { coins: 200, souls: 1, slayerPoints: 0 },
    repeatable: false,
    prerequisiteIds: ["q_unlock_zone2"],
    order: 75,
  },

  // Zone 3: Endgame (4 quests)
  {
    id: "q_unlock_zone3",
    title: "Shadow's Call",
    description: "Unlock the Shadowfell Citadel.",
    type: "unlock_zone",
    target: 1,
    zoneId: "shadowfell_citadel",
    reward: { coins: 500, souls: 4, slayerPoints: 1 },
    repeatable: false,
    prerequisiteIds: ["q_zone2_stage_clear"],
    order: 90,
  },
  {
    id: "q_zone3_stage_clear",
    title: "Abyss Walker",
    description: "Reach Stage 5.",
    type: "reach_stage",
    target: 5,
    reward: { coins: 600, souls: 5, slayerPoints: 2 },
    repeatable: false,
    prerequisiteIds: ["q_unlock_zone3"],
    order: 100,
  },
  {
    id: "q_zone3_boss",
    title: "Citadel Conqueror",
    description: "Defeat a boss in the Shadowfell Citadel.",
    type: "kill_boss_zone",
    target: 1,
    zoneId: "shadowfell_citadel",
    isBossCheck: true,
    reward: { coins: 800, souls: 6, slayerPoints: 1 },
    repeatable: false,
    prerequisiteIds: ["q_unlock_zone3"],
    order: 110,
  },
  {
    id: "q_prestige_after_zone3",
    title: "Eternal Cycle",
    description: "Prestige after unlocking the Shadowfell Citadel.",
    type: "prestige",
    target: 2,
    reward: { coins: 0, souls: 0, slayerPoints: 3 },
    repeatable: false,
    prerequisiteIds: ["q_unlock_zone3"],
    order: 120,
  },

  // Repeatable
  {
    id: "q_daily_grind",
    title: "Relentless Slayer",
    description: "Defeat 100 enemies anywhere.",
    type: "kill_any",
    target: 100,
    reward: { coins: 300, souls: 2, slayerPoints: 0 },
    repeatable: true,
    prerequisiteIds: [],
    order: 200,
  },
];

export function getQuestById(questId) {
  return QUESTS.find((q) => q.id === questId);
}